# Exports
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  history
  z
  sudo
  copypath
  dirhistory
  web-search
)

source $ZSH/oh-my-zsh.sh

# Bin exports
export PATH="$HOME/.cargo/bin:$PATH"

# Aliases
alias j='just'
alias n='nvim'
