clean:
    rm -rf zig-out zig-cache .zig-cache

b:
    zig build

br:
    zig build -Doptimize=ReleaseSafe

r:
    zig build run

t:
    zig build test

fmt:
    zig fmt src

fmt-check:
    zig fmt --check src

loc:
    find src -name "*.zig" | xargs wc -l

help:
    @just --list
